baseURL = "https://laughing-liskov-db83d0.netlify.com/"
languageCode = "en-us"
summarylength = 40
disqusShortname = "happy-green-sprout"
googleAnalytics = "UA-168575542-1"
relativeURLs = true
paginate = 100



[params]
    title = "Happy Green Sprout"
    subtitle = ""
    maintagline = "Happy and healthy with whole foods."
    inst_access = "6231435589.1677ed0.332c3e67344341199033de030d5fb284"

[menu]

    [[menu.main]]
        identifier = "home"
        name="Home"
        url="/"
        weight = 10

    [[menu.main]]
        identifier = "work-with-me"
        name="Work With Me"
        url="/services"
        weight=20

    [[menu.main]]
        identifier = "recipes"
        name="Recipes"
        url="/recipes"
        weight=30

    [[menu.main]]
        identifier = "blog"
        name="Blog"
        url="/blog"
        weight=40

    [[menu.main]]
        identifier = "contact"
        name="Contact"
        url="/contact"
        weight=50

[link]

    [[link.main]]
        description="hello"
        url="http://www.hello.com"

    [[link.main]]
        description="bye bye"
        url="http://www.bye.com"


